# Generated by Django 4.0.3 on 2022-04-25 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('educational_stats', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('local_govt', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=55)),
                ('gender', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=55)),
                ('other_name', models.CharField(blank=True, max_length=55)),
                ('last_name', models.CharField(blank=True, max_length=55)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
