# Generated by Django 4.0.3 on 2022-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_profile_profesion_profile_bio_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phoneNumber',
        ),
    ]
