# Generated by Django 4.0.3 on 2022-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_name',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
