# Generated by Django 4.0.3 on 2022-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_profile_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='first_nameother_namelast_name'),
        ),
    ]
