# Generated by Django 4.0.3 on 2022-04-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0006_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
