# Generated by Django 4.0.3 on 2022-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0009_profile_educational_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profesion',
            new_name='profesion',
        ),
    ]
