# Generated by Django 4.0.3 on 2022-04-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0011_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
