# Generated by Django 4.0.3 on 2022-04-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0012_remove_profile_signup_confirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
